In [ ]:
#Assessment - Data cleaning with Pandas

In [ ]:
#Please import the file provided and answer the following questions:
#    1. How many songs are in the data set?
#    2. Which song was in the highest number of spotify playlists (in spotify playlists)?
#    3. What is the most common key songs are played on?
#    4. On average, do songs played in Major mode have a higher danceability than songs played in minor mode?

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('/Users/alexandermanta/Downloads/spotify_playlist_data.csv')

In [4]:
#1. How many songs are in the data set?

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            860 non-null    object
 1   artist(s)_name        856 non-null    object
 2   artist_count          860 non-null    int64
 3   released_year         859 non-null    float64
 4   released_month        860 non-null    int64
 5   released_day          860 non-null    int64
 6   in_spotify_playlists  860 non-null    int64
 7   in_spotify_charts     860 non-null    int64
 8   streams               860 non-null    object
 9   in_apple_playlists    860 non-null    int64
 10  in_apple_charts       860 non-null    int64
 11  in_deezer_playlists   860 non-null    object
 12  in_deezer_charts      860 non-null    int64
 13  in_shazam_charts      819 non-null    object
 14  bpm                   860 non-null    int64
 15  key                   858 non-null    object
 16  mode                  860 non-null    object
 17  danceability_%        860 non-null    int64
 18  valence_%             860 non-null    int64
 19  energy_%              860 non-null    int64
 20  acousticness_%        860 non-null    int64
 21  instrumentalness_%    860 non-null    int64
 22  liveness_%            860 non-null    int64
 23  speechiness_%         860 non-null    int64
dtypes: float64(1), int64(16), object(7)
memory usage: 161.4+ KB

In [5]:
#2. Which song was in the highest number of spotify playlists (in spotify playlists)?

df.sort_values(by = 'in_spotify_playlists').iloc[-1,0]

'Get Lucky - Radio Edit'

In [6]:
#3. What is the most common key songs are played on?

df.key.describe()

count     858
unique     11
top        C#
freq      119
Name: key, dtype: object

In [7]:
#4. On average, do songs played in Major mode have a higher danceability than songs played in minor mode?

df.sort_values(by='danceability_%').iloc[-1,16]

'Minor'

In [8]:
#Make a copy of your data

In [9]:
df_clean = df.copy()

In [10]:
#Inspect you data
df_clean.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023.0,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023.0,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023.0,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019.0,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023.0,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6

In [11]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            860 non-null    object
 1   artist(s)_name        856 non-null    object
 2   artist_count          860 non-null    int64
 3   released_year         859 non-null    float64
 4   released_month        860 non-null    int64
 5   released_day          860 non-null    int64
 6   in_spotify_playlists  860 non-null    int64
 7   in_spotify_charts     860 non-null    int64
 8   streams               860 non-null    object
 9   in_apple_playlists    860 non-null    int64
 10  in_apple_charts       860 non-null    int64
 11  in_deezer_playlists   860 non-null    object
 12  in_deezer_charts      860 non-null    int64
 13  in_shazam_charts      819 non-null    object
 14  bpm                   860 non-null    int64
 15  key                   858 non-null    object
 16  mode                  860 non-null    object
 17  danceability_%        860 non-null    int64
 18  valence_%             860 non-null    int64
 19  energy_%              860 non-null    int64
 20  acousticness_%        860 non-null    int64
 21  instrumentalness_%    860 non-null    int64
 22  liveness_%            860 non-null    int64
 23  speechiness_%         860 non-null    int64
dtypes: float64(1), int64(16), object(7)
memory usage: 161.4+ KB

In [ ]:
#Streams is object
#Year is float
#Missing values

In [14]:
#Check for duplicates

#Duplicated on the dataframe
df.duplicated().sum()

2

In [17]:
df_clean[df_clean.duplicated(keep=False, subset = ['artist(s)_name'])]

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
2,vampire,Olivia Rodrigo,1,2023.0,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019.0,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023.0,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
7,Columbia,Quevedo,1,2023.0,7,7,714,43,58149378,25,...,100,F,Major,67,26,71,37,0,11,4
11,Super Shy,NewJeans,1,2023.0,7,7,422,55,58255150,37,...,150,F,Minor,78,52,82,18,0,15,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
852,BackOutsideBoyz,Drake,1,2022.0,11,4,1045,0,93367537,8,...,142,F,Minor,85,40,43,4,0,39,32
853,Broke Boys,"Drake, 21 Savage",2,2022.0,11,4,1060,0,106249219,3,...,120,D,Major,64,11,53,1,0,25,27
854,The Great War,Taylor Swift,1,2022.0,10,21,1274,0,181382590,1,...,96,F,Major,57,55,74,22,0,8,4
856,Bigger Than The Whole Sky,Taylor Swift,1,2022.0,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
859,Alone,Burna Boy,1,2022.0,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

In [21]:
#Getting rid of dupplicates

df_clean.drop_duplicates(inplace = True)

In [22]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 858 entries, 0 to 859
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            858 non-null    object
 1   artist(s)_name        854 non-null    object
 2   artist_count          858 non-null    int64
 3   released_year         857 non-null    float64
 4   released_month        858 non-null    int64
 5   released_day          858 non-null    int64
 6   in_spotify_playlists  858 non-null    int64
 7   in_spotify_charts     858 non-null    int64
 8   streams               858 non-null    object
 9   in_apple_playlists    858 non-null    int64
 10  in_apple_charts       858 non-null    int64
 11  in_deezer_playlists   858 non-null    object
 12  in_deezer_charts      858 non-null    int64
 13  in_shazam_charts      817 non-null    object
 14  bpm                   858 non-null    int64
 15  key                   856 non-null    object
 16  mode                  858 non-null    object
 17  danceability_%        858 non-null    int64
 18  valence_%             858 non-null    int64
 19  energy_%              858 non-null    int64
 20  acousticness_%        858 non-null    int64
 21  instrumentalness_%    858 non-null    int64
 22  liveness_%            858 non-null    int64
 23  speechiness_%         858 non-null    int64
dtypes: float64(1), int64(16), object(7)
memory usage: 167.6+ KB

In [24]:
#Give all column names
df_clean.columns

Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts',
       'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts', 'bpm',
       'key', 'mode', 'danceability_%', 'valence_%', 'energy_%',
       'acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%'],
      dtype='object')

In [28]:
df_clean.drop(columns = ['in_shazam_charts','instrumentalness_%','energy_%'], inplace = True)

In [29]:
df_clean.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,in_deezer_playlists,in_deezer_charts,bpm,key,mode,danceability_%,valence_%,acousticness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023.0,7,14,553,147,141381703,43,...,45,10,125,B,Major,80,89,31,8,4
1,LALA,Myke Towers,1,2023.0,3,23,1474,48,133716286,48,...,58,14,92,C#,Major,71,61,7,10,4
2,vampire,Olivia Rodrigo,1,2023.0,6,30,1397,113,140003974,94,...,91,14,138,F,Major,51,32,17,31,6
3,Cruel Summer,Taylor Swift,1,2019.0,8,23,7858,100,800840817,116,...,125,12,170,A,Major,55,58,11,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023.0,5,18,3133,50,303236322,84,...,87,15,144,A,Minor,65,23,14,11,6

In [31]:
df_clean.drop(['valence_%','speechiness_%'], axis =1, inplace = True)

In [32]:
df_clean.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,bpm,key,mode,danceability_%,acousticness_%,liveness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023.0,7,14,553,147,141381703,43,263,45,10,125,B,Major,80,31,8
1,LALA,Myke Towers,1,2023.0,3,23,1474,48,133716286,48,126,58,14,92,C#,Major,71,7,10
2,vampire,Olivia Rodrigo,1,2023.0,6,30,1397,113,140003974,94,207,91,14,138,F,Major,51,17,31
3,Cruel Summer,Taylor Swift,1,2019.0,8,23,7858,100,800840817,116,207,125,12,170,A,Major,55,11,11
4,WHERE SHE GOES,Bad Bunny,1,2023.0,5,18,3133,50,303236322,84,133,87,15,144,A,Minor,65,14,11